---
title: "Schedule"
---

---

## Week 1

### Wed, Aug 23

- Topics
    + Structure of the course
    + Why biological psychology? Read: BW 1
    + Methods in neuroscience <https://en.wikibooks.org/wiki/Cognitive_Psychology_and_Cognitive_Neuroscience/Behavioural_and_Neuroscience_Methods>.
- Materials
    + Lecture notes | [HTML slides](lectures/511-2017-08-23.html) |
    + More on [MRI physics](https://www.youtube.com/watch?v=Ok9ILIYzmaY)

### Fri, Aug 25

- Topics
    + Methods in neuroscience, 2:49-57, 3:84-89.
- Materials
    + Lecture notes | [HTML slides](lectures/511-2017-08-25.html) |
    <!-- + <https://en.wikibooks.org/wiki/Cognitive_Psychology_and_Cognitive_Neuroscience/Behavioural_and_Neuroscience_Methods> -->
    + Cohen, M. X. (2017). Where Does EEG Come From and What Does It Mean? Trends in neurosciences, 40(4), 208–218. Retrieved from <http://dx.doi.org/10.1016/j.tins.2017.02.004>
    + Logothetis, N. K., Pauls, J., Augath, M., Trinath, T., & Oeltermann, A. (2001). Neurophysiological investigation of the basis of the fMRI signal. Nature, 412(6843), 150–157. Retrieved January 20, 2016, from <http://www.nature.com/nature/journal/v412/n6843/abs/412150a0.html>
    + Hillman, E. M. C. (2014). Coupling mechanism and significance of the BOLD signal: a status report. Annual review of neuroscience, 37, 161–181. Retrieved from <http://dx.doi.org/10.1146/annurev-neuro-071013-014111>.

---

## Week 2

### Wed, Aug 30

- Topics
    + Neuroanatomy. Read BW 2:34-49.
- Materials
    + Lecture notes | [HTML slides](lectures/511-2017-08-30-anatomy.html) |
 
### Fri, Sep 1

- Topics
    + Neuroanatomy. Read BW 2:34-49.
- Materials
    + Lecture notes | [HTML slides](lectures/511-2017-09-01-anatomy-II.html) |

---

## Week 3

### Wed, Sep 6

- Topics
    + Wrap-up on neuroanatomy
    + **Neuroanatomy Lab**.
- Materials
    + Lecture notes | [HTML slides](lectures/511-2017-09-01-anatomy-II.html) |
    + [Anatomy lab handout](handout/neuroanatomy-lab-handout.pdf)

### Fri, Sep 8

- Topics
    + **Neuroanatomy Lab**.

---

## Week 4

### Wed, Sep 13

- Topics
    + Cellular neuroanatomy. Read BW 2:23-33. 
- Supplemental Materials
    + Zeng, H., & Sanes, J. R. (2017). Neuronal cell-type classification: challenges, opportunities and the path forward. *Nature Reviews Neuroscience*. Retrieved from <http://dx.doi.org/10.1038/nrn.2017.85>.
    + Oliveira, J. F., Sardinha, V. M., Guerra-Gomes, S., Araque, A., & Sousa, N. (2015). Do stars govern our actions? Astrocyte involvement in rodent behavior. *Trends in Neurosciences*, *38*(9), 535–549. Retrieved from http://dx.doi.org/10.1016/j.tins.2015.07.006
- Materials
    + Lecture notes | [HTML slides](lectures/511-2017-09-13-cells.html) |

### Fri, Sep 15

- Topics
    + **Quiz 1**. | [Download](quiz/quiz-01/511-quiz-1.pdf) |. Due at start of class on Wednesday, September 20, 2017.
    + Neurophysiology. Read BW 3:57-73.
- Materials
    + Lecture notes | [HTML slides](lectures/511-2017-09-15-neurophys.html) |

---

## Week 5

### Wed, Sep 20,

- Topics
    + Neural communication. Read BW 3:55-89.
- Materials
    + Lecture notes | [HTML slides](lectures/511-2017-09-20-neurophys-II.html) |

### Fri, Sep 22

- Topics
    + Neurochemistry. Read BW: 4:107-124.

---

## Week 6

### Wed, Sep 27

- Topics
    + Neurochemistry. Read BW: 4:107-124.

### Fri Sep 29

- Topics
    + Hormones. 5:125-154.
- Materials
    + Gao, X.-B., & Horvath, T. (2014). Function and dysfunction of hypocretin/orexin: an energetics point of view. Annual review of neuroscience, 37, 101–116. Retrieved from <http://dx.doi.org/10.1146/annurev-neuro-071013-013855>

---

## Week 7

### Wed, Oct 4

- Topics
    + Evolution. Read BW 6 & 7. Optional [Hofman 2014](http://www.frontiersin.org/Journal/Abstract.aspx?s=742&name=neuroanatomy&ART_DOI=10.3389/fnana.2014.00015).
- Supplemental Materials
    + Rakic, P. (2009). Evolution of the neocortex: a perspective from developmental biology. Nature reviews. Neuroscience, 10(10), 724–735. Retrieved October 5, 2015, from <http://www.nature.com/nrn/journal/v10/n10/abs/nrn2719.html>.

### Fri, Oct 6

- Topics
    + Development. Read BW 6 & 7. Optional [Hofman 2014](http://www.frontiersin.org/Journal/Abstract.aspx?s=742&name=neuroanatomy&ART_DOI=10.3389/fnana.2014.00015).
- Supplemental Materials
    + Cao, M., Huang, H., & He, Y. (2017). Developmental Connectomics from Infancy through Early Childhood. Trends in neurosciences, 40(8), 494–506. Retrieved from <http://dx.doi.org/10.1016/j.tins.2017.06.003>

---

## Week 8

### Wed, Oct 11

- Topics
    + **Quiz 2**.
    + Perception. Read BW 8:223-247.
- Supplemental Materials

### Fri, Oct 13

- Topics
    + Perception. Read BW 8:223-247.
- Supplemental Materials
    + Murray, M. M., Lewkowicz, D. J., Amedi, A., & Wallace, M. T. (2016). Multisensory Processes: A Balancing Act across the Lifespan. Trends in neurosciences, 39(8), 567–579. Retrieved July 28, 2016, from http://www.sciencedirect.com/science/article/pii/S0166223616300480

---

## Week 9

### Wed, Oct 18

- Topics
    + Action
- Supplemental Materials
    + Nielsen, J. B. (2016). Human Spinal Motor Control. Annual review of neuroscience, 39, 81–101. Retrieved from <http://dx.doi.org/10.1146/annurev-neuro-070815-013913>

### Fri, Oct 20

- Topics
    + Action
- Supplemental Materials
    + Shenoy, K. V., Sahani, M., & Churchland, M. M. (2013). Cortical control of arm movements: a dynamical systems perspective. Annual review of neuroscience, 36, 337–359. Retrieved from <http://dx.doi.org/10.1146/annurev-neuro-062111-150509>.

---

## Week 10

### Wed, Oct 25

- Topics
    + Cognition. Read BW 17, 18, 19.
- Supplemental Materials
    + Hagoort, P., & Indefrey, P. (2014). The neurobiology of language beyond single words. Annual review of neuroscience, 37, 347–362. Retrieved from <http://dx.doi.org/10.1146/annurev-neuro-071013-013847>.

### Fri, Oct 27

- Topics
    + Learning & memory
- Supplemental Materials
    + Squire, L. R., & Wixted, J. T. (2011). The cognitive neuroscience of human memory since H.M. Annual review of neuroscience, 34, 259–288. Retrieved from <http://dx.doi.org/10.1146/annurev-neuro-061010-113720>.

---

## Week 11

### Wed, Nov 1

- Topic
    + Emotion. Read BW 15.
- Supplemental Materials
    + Pellman, B. A., & Kim, J. J. (2016). What Can Ethobehavioral Studies Tell Us about the Brain’s Fear System? Trends in neurosciences, 39(6), 420–431. Retrieved from http://dx.doi.org/10.1016/j.tins.2016.04.001
    + Musazzi, L., Tornese, P., Sala, N., & Popoli, M. (2017). Acute or Chronic? A Stressful Question. Trends in neurosciences. Retrieved from <http://dx.doi.org/10.1016/j.tins.2017.07.002>

### Wed, Nov 3

- Topics
    + Emotion
- Supplemental Materials
    + Hu, H. (2016). Reward and Aversion. Annual review of neuroscience, 39, 297–324. Retrieved from <http://dx.doi.org/10.1146/annurev-neuro-070815-014106>
    + Watabe-Uchida, M., Eshel, N., & Uchida, N. (2017). Neural Circuitry of Reward Prediction Error. Annual review of neuroscience, 40, 373–394. Retrieved from <http://dx.doi.org/10.1146/annurev-neuro-072116-031109>

---

## Week 12

### Wed, Nov 8

- Topics
    + Disorder and Disease. Read BW 16.
- Supplemental Materials
    + Hunt, M. J., Kopell, N. J., Traub, R. D., & Whittington, M. A. (2017). Aberrant Network Activity in Schizophrenia. Trends in neurosciences, 40(6), 371–382. Retrieved from http://dx.doi.org/10.1016/j.tins.2017.04.003

### Fri, Nov 10

- Topics
    + Disorder and Disease. Read BW 16.
- Supplemental Materials
    + Pawluski, J. L., Lonstein, J. S., & Fleming, A. S. (2017). The Neurobiology of Postpartum Anxiety and Depression. Trends in neurosciences, 40(2), 106–120. Retrieved from http://dx.doi.org/10.1016/j.tins.2016.11.009
    + Namkung, H., Kim, S.-H., & Sawa, A. (2017). The Insula: An Underestimated Brain Area in Clinical Neuroscience, Psychiatry, and Neurology. Trends in neurosciences, 40(4), 200–207. Retrieved from http://dx.doi.org/10.1016/j.tins.2017.02.002
    + Volk, L., Chiu, S.-L., Sharma, K., & Huganir, R. L. (2015). Glutamate synapses in human cognitive disorders. Annual review of neuroscience, 38, 127–149. Retrieved from <http://dx.doi.org/10.1146/annurev-neuro-071714-033821>

---

## Week 13

### Wed, Nov 15

- Topics
    + **Quiz 3**
    + Catch-up day
    
### Fri, Nov 22

- Topics
    - Prep for student presentations

---

## Thanksgiving Break, November 20 - 24, 2017

---

## Week 14

### Wed Nov, 29

- Topics
    - Prep for student presentations

### Fri, Dec 1

- Topics
    - Student presentation Group A
    - Student presentation Group B

---

## Week 15

### Wed, Dec 6

- Topics
    - Student presentation Group C
    - Student presentation Group D

### Fri, Dec 8

- Topics
    + Networks all the way down
- Supplemental Materials
    + Swanson, L. W., & Lichtman, J. W. (2016). From Cajal to Connectome and Beyond. Annual review of neuroscience, 39, 197–216. Retrieved from <http://dx.doi.org/10.1146/annurev-neuro-071714-033954>
    + Raichle, M. E. (2015). The brain’s default mode network. Annual review of neuroscience, 38, 433–447. Retrieved from <http://dx.doi.org/10.1146/annurev-neuro-071013-014030>.
    + Sarkar, A., Lehto, S. M., Harty, S., Dinan, T. G., Cryan, J. F., & Burnet, P. W. J. (2016). Psychobiotics and the Manipulation of Bacteria-Gut-Brain Signals. Trends in neurosciences, 39(11), 763–781. Retrieved from http://dx.doi.org/10.1016/j.tins.2016.09.002
